# Generated by Django 2.1.5 on 2019-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='citizenregister',
            name='status',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
