# Generated by Django 2.1.5 on 2019-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_citizen', '0002_auto_20190315_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='registerdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
