# Generated by Django 2.1.5 on 2019-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_citizen', '0003_auto_20190318_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='closedate',
            field=models.DateField(default=None),
        ),
    ]
