# Generated by Django 2.1.5 on 2019-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_citizen', '0004_auto_20190319_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='closedate',
            field=models.DateField(default=None, null=True),
        ),
    ]
