# Generated by Django 2.1.5 on 2019-03-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='officer/')),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_admin.Department')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_login.Login')),
            ],
        ),
    ]
